spring:
  application:
    name: backend-to-do
  datasource:
    url: jdbc:mysql://localhost:3307/to_do_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8080
  servlet:
    context-path: /api/v1

